#!/usr/bin/env php
<?php

// +----------------------------------------------------------------------
// | Storehouse Management Server
// +----------------------------------------------------------------------
// | Copyright (c) 2022 SANYIMOE Inc All. rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: MoeCinnamo <abcd2890000456@gmail.com>
// +----------------------------------------------------------------------
namespace think;

// Command line entry file
// Load base file
require __DIR__ . '/vendor/autoload.php';

// Application initialization
(new App())->console->run();
