name: CI

on:
  push:
    branches:
      - dev
    paths-ignore:
      - 'app/lang/**'
      - '**.md'
  pull_request:
    branches:
      - dev
    paths-ignore:
      - 'app/lang/**'
      - '**.md'
      
jobs:
  build:
    runs-on: ubuntu-lastest
    strategy:
      matrix:
        php: [7.3]
      fail-fast: false
    services:
      redis:
        image: redis
        posts:
          - 6379:6379
      steps:
        - uses: actions/checkout@v2
        - name: Set up PHP ${{matrix.php}}
        - uses: actions/setup-php@v2
      with:
        php-version: ${{matrix.php}}
    - name: Run test
      run: mvn test
    - name: Build with Maven
      run: mvn package -Dmaven.test.skip=true
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{secrets.CODECOV_TOKEN}}
