name: CI

on:
  push:
    branches:
      - dev
    paths-ignore:
      - 'app/lang/**'
      - '**.md'
  pull_request:
    branches:
      - dev
    paths-ignore:
      - 'app/lang/**'
      - '**.md'

jobs:
  php-lint:
    name: PHP Linting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.3
        coverage: none
        extensions: mbstring, dom, fileinfo, gd
    - name: Install dependencies
      run: |
        composer install
    - name: Prepare
      run: |
        php think service:discover
        php think vendor:publish
  php:
    name: PHP ${{ matrix.php }} Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['7.3', '7.4', '8.0', '8.1']
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup PHP only
      uses: shivammathur/setup-php@v2
      if: matrix.php != '7.3'
      with:
        php-version: ${{ matrix.php }}
        coverage: none
        extensions: mbstring, dom, sqlite, gd, zip
    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-
    - name: Install Composer dependencies
      run: composer install
    - name: Setup PHP with Xdebug
      uses: shivammathur/setup-php@v2
      if: matrix.php == '7.3'
      with:
        php-version: ${{ matrix.php }}
        coverage: xdebug
        extensions: mbstring, dom, sqlite, gd, zip
    - name: Cache Composer dependencies
      uses: actions/cache@v1
      with:
        path: vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-
    - name: Install Composer dependencies
      run: composer install
    - name: Run tests only
      if: matrix.php != '8.0'
      run: ./vendor/bin/phpunit
    - name: Run tests with coverage report
      if: matrix.php == '8.0'
      run: ./vendor/bin/phpunit --coverage-clover=coverage.xml
    - name: Upload coverage report
      uses: codecov/codecov-action@v1
      if: matrix.php == '7.3' && success()
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        name: github-actions
  lint:
    name: Frontend Linting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  jest:
    name: Frontend Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Upload coverage report
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        name: github-actions
